// Generated by `node scripts/export-content.mjs` from Redis (content:domains).
// Edit content in Redis and re-run the export, not this file directly.
export const DOMAINS_LIST = [
  {
    "id": 1,
    "slug": "1-agentic-architecture",
    "name": "Agentic Architecture & Orchestration",
    "short": "Agentic Architecture",
    "weight": 27,
    "color": "#6C5CE0",
    "blurb": "Agent loops, stop_reason control, coordinator/subagent patterns, context passing, parallel vs sequential orchestration, and multi-agent system design."
  },
  {
    "id": 2,
    "slug": "2-tool-design-mcp",
    "name": "Tool Design & MCP Integration",
    "short": "Tools & MCP",
    "weight": 18,
    "color": "#1AA6B7",
    "blurb": "Tool schemas, tool_use / tool_result blocks, the Model Context Protocol (servers, clients, transports), MCP primitives, and robust tool design."
  },
  {
    "id": 3,
    "slug": "3-claude-code-config",
    "name": "Claude Code Configuration & Workflows",
    "short": "Claude Code",
    "weight": 20,
    "color": "#1F9D6B",
    "blurb": "CLAUDE.md, settings.json, permissions, slash commands, hooks, subagents, plan mode, MCP config, and day-to-day Claude Code workflows."
  },
  {
    "id": 4,
    "slug": "4-prompt-engineering",
    "name": "Prompt Engineering & Structured Output",
    "short": "Prompt Engineering",
    "weight": 20,
    "color": "#C6841E",
    "blurb": "XML structuring, few-shot, chain-of-thought, prefill, role prompts, JSON/structured output, and prompt anti-patterns."
  },
  {
    "id": 5,
    "slug": "5-context-management",
    "name": "Context Management & Reliability",
    "short": "Context & Reliability",
    "weight": 15,
    "color": "#C4453B",
    "blurb": "Context windows, prompt caching, token budgeting, compaction, retries/idempotency, evals, and production reliability."
  }
];
