// Generated by `node scripts/export-content.mjs` from Redis (content:faq).
// Edit content in Redis and re-run the export, not this file directly.
export const FAQ_ITEMS = [
  [
    "Is Claude Cert Prep free?",
    "Yes. Every practice mode, the full mock exam, the diagnostic, drill, curriculum, glossary, and quick reference are free with no account or sign-up required."
  ],
  [
    "How long does it take to prepare for the CCA-F exam?",
    "Most people need about two to three weeks at roughly one hour a day, mostly spent on practice questions rather than reading — assuming around six months of hands-on Claude API or Claude Code experience going in."
  ],
  [
    "Is this an official Anthropic study resource?",
    "No. Claude Cert Prep is an independent, unofficial study aid. It is not affiliated with, endorsed by, or sponsored by Anthropic."
  ],
  [
    "What's the CCA-F exam format?",
    "60 scenario-based questions in 120 minutes, scored on a scaled 100-1000 range with a pass mark of 720, weighted across five domains."
  ],
  [
    "Do I need an account to track my progress?",
    "No — progress, flags, and mock-exam history are saved locally in your browser by default, with no account or sign-up required to practice. If you want that history to follow you across devices, you can optionally create a free account after finishing a practice set; only your progress data (no question content) syncs, and it's tied to your account, not shared or sold."
  ]
];
