// Generated by `node scripts/export-content.mjs` from Redis (content:glossary).
// Edit content in Redis and re-run the export, not this file directly.
export const GLOSSARY = {
  "1": [
    [
      "Agentic loop",
      "The model calls a tool, the client executes it and returns the result, and the cycle repeats until the model stops requesting tools.",
      "The only correct termination signal is <code>stop_reason</code> — not parsing the assistant's text for phrases like \"I'm done.\""
    ],
    [
      "stop_reason",
      "The Messages API field explaining why generation stopped: <code>end_turn</code>, <code>tool_use</code>, <code>max_tokens</code>, or <code>stop_sequence</code>.",
      "Exam questions test whether you branch loop control on this field or on something fragile like text content."
    ],
    [
      "Orchestrator-workers",
      "A lead agent decomposes a task, dispatches subtasks to worker subagents, then synthesizes their results into one output.",
      "Pick this pattern when subtasks aren't fully predictable in advance and need dynamic decomposition."
    ],
    [
      "Hub-and-spoke topology",
      "Subagents report only to the orchestrator and never communicate with each other directly.",
      "A distractor answer that has subagents messaging each other peer-to-peer is always wrong for this exam's model."
    ],
    [
      "Prompt chaining",
      "A fixed sequence of LLM calls where each step's output feeds directly into the next step's input.",
      "Correct when a task decomposes cleanly into ordered subtasks — not when subtasks are independent (that's parallelization)."
    ],
    [
      "Routing",
      "Classify the input first, then send it down one of several specialized prompt or model paths.",
      "Use when inputs fall into distinct categories that genuinely need different handling, not just different phrasing."
    ],
    [
      "Parallelization",
      "Run independent subtasks concurrently (sectioning) or run the same task multiple times for consensus (voting).",
      "Sectioning splits work; voting improves confidence on a single judgment call — know which the scenario calls for."
    ],
    [
      "Evaluator-optimizer",
      "One call generates a response, a second evaluates it against explicit criteria and returns feedback for revision, looped until it passes.",
      "Exam scenarios use this when quality criteria are clear but generation quality alone isn't reliable enough."
    ],
    [
      "Context isolation",
      "Giving each subagent only the context it needs for its scoped task, not the orchestrator's full history.",
      "Protects both token cost and focus — a subagent drowning in irrelevant context is a common exam anti-pattern."
    ],
    [
      "Subagent invocation",
      "The parent spins up a subagent with a scoped prompt and toolset; it returns a final result, not a full transcript.",
      "Watch for options that have the orchestrator forwarding raw subagent transcripts back into its own context — usually wrong."
    ]
  ],
  "2": [
    [
      "Tool schema",
      "The JSON Schema describing a tool's name, description, and input parameters that the model uses to decide when and how to call it.",
      "A vague tool description is a bigger source of exam-tested failures than a vague tool name."
    ],
    [
      "tool_use block",
      "The content block the model emits when it wants to call a tool: includes the tool name, a unique id, and structured input.",
      "Distinguish from <code>tool_result</code>, which is what the client sends back, not what the model sends."
    ],
    [
      "tool_result block",
      "The message the client returns containing a tool's output, matched to a <code>tool_use</code> id, optionally flagged <code>is_error</code>.",
      "Returning raw stack traces instead of a structured, actionable error is a textbook wrong answer."
    ],
    [
      "Model Context Protocol (MCP)",
      "An open protocol standardizing how AI applications connect to external tools, data sources, and prompt templates.",
      "Know the vocabulary precisely — MCP is tested on terminology, not just concept recognition."
    ],
    [
      "MCP server / client / host",
      "A server exposes tools, resources, and prompts; a client keeps a 1:1 connection to one server; a host is the application coordinating multiple clients.",
      "Claude Code is a host; each MCP server it connects to gets its own client connection."
    ],
    [
      "MCP primitives",
      "Tools (model-invoked actions), Resources (contextual data the app can read), and Prompts (reusable templates) exposed by a server.",
      "The exam distinguishes these by who invokes them: the model invokes tools; the user or app invokes resources and prompts."
    ],
    [
      "Transport",
      "How an MCP client and server communicate — stdio for a local subprocess, or Streamable HTTP for a remote server.",
      "Local, trusted integrations lean stdio; remote or shared servers need HTTP with its own auth story."
    ],
    [
      "Structured error responses",
      "Returning <code>is_error: true</code> with a clear, actionable message in a tool result so the model can self-correct.",
      "The exam rewards designs where a failed tool call gives the model enough signal to retry correctly, not just fail."
    ],
    [
      "Tool distribution choice",
      "Deciding whether a capability should be a built-in tool, an MCP server, or a slash command/skill — driven by who needs it and how often it changes.",
      "A capability only one project needs rarely justifies a standalone MCP server over a project-local skill."
    ],
    [
      "Built-in tools",
      "First-party tools like Bash, the text editor, and web search/fetch, usable without standing up an MCP server.",
      "Reach for a built-in tool before building custom infrastructure that duplicates one."
    ]
  ],
  "3": [
    [
      "CLAUDE.md",
      "A memory file automatically pulled into context documenting project conventions, commands, and constraints.",
      "Multiple CLAUDE.md files can exist at different scopes and are all included — none of them get silently dropped."
    ],
    [
      "CLAUDE.md hierarchy",
      "Enterprise, user, project, and local CLAUDE.md files are merged together, with more specific scopes layered on top of general ones.",
      "A common wrong answer assumes the most specific file replaces the others — it's additive, not a full override."
    ],
    [
      "settings.json",
      "Project- or user-level configuration for permissions, hooks, environment variables, and other Claude Code behavior.",
      "Know which settings are safe to check into a repo (project-shared) versus which belong in a local, git-ignored file."
    ],
    [
      "Permissions",
      "Allow / deny / ask rules controlling which tools and commands Claude Code can run without prompting the user.",
      "Scenario questions test picking the narrowest permission that still lets the workflow function."
    ],
    [
      "Slash command",
      "A reusable, user-invoked prompt template stored as a Markdown file and triggered explicitly with <code>/name</code>.",
      "The user has to type it — contrast with a skill, which Claude can invoke on its own judgment."
    ],
    [
      "Skill",
      "A packaged, discoverable capability — instructions plus optional scripts — that Claude can invoke autonomously when it judges it relevant.",
      "If a scenario needs Claude to decide when to use it, that rules out a slash command as the right mechanism."
    ],
    [
      "Hook",
      "A shell command that fires automatically on a lifecycle event (e.g. PreToolUse, PostToolUse, Stop) to enforce policy deterministically.",
      "Hooks exist specifically because prompted instructions ('please always run tests first') aren't reliably deterministic."
    ],
    [
      "Plan mode",
      "A read-only mode where Claude researches and proposes an approach before any file is edited, requiring explicit approval to proceed.",
      "Correct answer for scenarios needing human sign-off before risky or hard-to-reverse changes."
    ],
    [
      "Subagents (Claude Code)",
      "Separately configured agents with their own system prompt and tool access, delegated a scoped piece of work by the main agent.",
      "Distinguish product-level Claude Code subagents from the general agentic-architecture subagent pattern in Domain 1 — related, not identical."
    ],
    [
      "CI/CD integration",
      "Running Claude Code non-interactively (headless mode) inside a pipeline, e.g. for automated review or fix-and-PR workflows.",
      "Headless runs still need explicit permission configuration — they don't get an interactive prompt to fall back on."
    ]
  ],
  "4": [
    [
      "System prompt",
      "The top-level instruction set establishing role, constraints, and behavior for the whole conversation.",
      "Distinct from a per-turn user message — the exam tests knowing which behaviors belong in which layer."
    ],
    [
      "XML structuring",
      "Wrapping distinct prompt components — instructions, context, examples — in XML-like tags so the model reliably tells them apart.",
      "Especially valuable for long prompts mixing several kinds of content in one request."
    ],
    [
      "Few-shot prompting",
      "Including 2–5 worked examples in the prompt to show the exact input/output pattern wanted.",
      "More reliable than instructions alone when the desired output format is precise and easy to demonstrate but hard to describe."
    ],
    [
      "Chain-of-thought",
      "Asking the model to reason step by step before answering, improving accuracy on multi-step problems at the cost of latency and tokens.",
      "Not free — the exam expects you to reserve it for genuinely multi-step reasoning, not simple lookups."
    ],
    [
      "Prefill",
      "Seeding the start of the assistant's response to force a format — e.g. starting with <code>{</code> to guarantee JSON — or skip preamble.",
      "A fast, cheap way to eliminate an entire class of formatting failures without extra validation logic."
    ],
    [
      "Structured output",
      "Constraining the model's response to a defined schema so downstream code can parse it reliably.",
      "The exam distinguishes 'ask nicely for JSON' from actually constraining and validating the output."
    ],
    [
      "Validation/retry loop",
      "Programmatically validating a structured response against its schema and re-prompting with the specific error on failure.",
      "The retry prompt must include what specifically failed — a bare 'try again' rarely fixes the same mistake twice."
    ],
    [
      "Batch processing",
      "Using an asynchronous batch API to process many independent prompts at lower cost when latency isn't critical.",
      "Correct choice for large, non-interactive workloads; wrong choice whenever a user is waiting on the response."
    ],
    [
      "Multi-pass review",
      "Splitting generation and review into separate calls so the reviewing pass isn't anchored by the generation pass's own reasoning.",
      "A single call asked to 'write and then check your own work' tends to rubber-stamp itself — the exam flags this."
    ],
    [
      "Prompt anti-pattern",
      "Common mistakes like negative-only instructions ('don't do X') with no positive alternative, or one prompt overloaded with unrelated tasks.",
      "When an option only tells the model what not to do, look for a sibling option that also states the desired behavior."
    ]
  ],
  "5": [
    [
      "Context window",
      "The finite token budget available for a request — input history and output share this same budget.",
      "Budgeting questions expect you to account for tool definitions and retrieved data, not just the conversation text."
    ],
    [
      "Prompt caching",
      "Marking a stable prefix of a prompt as cacheable so repeated requests reuse it server-side, cutting latency and cost.",
      "Only the portion before the first change is reusable — appending new content after a cached prefix keeps the cache hit."
    ],
    [
      "Token budgeting",
      "Deliberately allocating context space between system prompt, tool definitions, retrieved data, and history so nothing critical is crowded out.",
      "The exam rewards proactively trimming low-value context over reactively hitting the limit and truncating blindly."
    ],
    [
      "Compaction / summarization",
      "Condensing older conversation history into a summary to free context space.",
      "The 'summarization trap': over-compacting drops details the model still needs, producing vague, ungrounded later responses."
    ],
    [
      "Escalation on ambiguity",
      "Surfacing uncertainty to a human rather than silently guessing when a decision is high-stakes or underspecified.",
      "Correct answers favor escalation exactly when reversibility is low and confidence is uncertain — not for every judgment call."
    ],
    [
      "Error propagation",
      "Deciding whether a subagent's error should halt the parent process, trigger a retry, or surface as a degraded-but-continuing result.",
      "Silently swallowing every subagent error is as wrong as halting on every one — the right call depends on the task's criticality."
    ],
    [
      "Idempotency",
      "Designing a tool call so running it twice has the same effect as running it once.",
      "Essential for anything that might get automatically retried — non-idempotent actions (like sending an email) need a guard."
    ],
    [
      "Codebase exploration",
      "An agent's strategy for building situational context — grep/search first vs. reading whole files — before making changes.",
      "Exam scenarios reward targeted exploration over reflexively reading every file in a large repo."
    ],
    [
      "Evals",
      "A structured test suite scoring agent or prompt outputs against expected behavior, used to catch regressions before shipping.",
      "Treat evals as the mechanism that turns 'it seemed to work when I tried it' into something you can actually trust."
    ],
    [
      "Information provenance",
      "Tracking where a piece of context came from — which tool call, file, or turn — so it can be trusted appropriately.",
      "Matters most when a model must reconcile conflicting information from two different sources in the same context."
    ]
  ]
};
