export const LESSONS = [
  {
    slug: "2-1-tool-schemas",
    title: "Designing Tool Schemas",
    dek: "How to write tool schemas the model will actually call correctly, and why description quality outranks naming.",
    minutes: 8,
    bodyHtml: `
      <p>A tool schema is JSON Schema attached to a tool definition: <code>name</code>, <code>description</code>, and <code>input_schema</code> describing the parameters. The model reads this schema at inference time and decides two things from it: whether to call the tool at all, and what arguments to pass. Nothing else is available to the model — no source code, no comments in your codebase, no tribal knowledge. If the schema is ambiguous, the model's behavior will be ambiguous.</p>
      <h2>Description beats name</h2>
      <p>Exam-relevant point: the model selects tools primarily from the <code>description</code> field, not the <code>name</code> field. A tool named <code>search</code> with a three-word description will be selected incorrectly far more often than a tool named <code>x1</code> with a precise, example-rich description. Treat the description as the primary interface contract, not the name. Good descriptions state: what the tool does, when to use it (and when not to), what each parameter means, units and formats for ambiguous fields (is a date a Unix timestamp or ISO 8601? is a price in cents or dollars?), and edge-case behavior (what happens on an empty result set, what happens if a required lookup fails).</p>
      <h2>Parameter design</h2>
      <p>Keep required parameters minimal and give optional parameters sane defaults described in the schema text itself, since the model cannot read your server-side default logic. Use <code>enum</code> constraints wherever the parameter space is closed — this reduces invalid calls far more effectively than prose alone. Prefer flat, explicit parameter names over deeply nested objects when the tool will be called frequently; nested structures increase the chance of malformed <code>tool_use</code> input, especially with smaller models. Where a parameter's format is easy to get wrong (a phone number, a currency code, a compound identifier), give one or two examples directly in the parameter's own description, not just in the top-level tool description.</p>
      <h2>Scoping tools</h2>
      <p>A single tool that does one well-defined thing is easier for the model to select correctly than one tool with a mode flag that switches between five behaviors. If you find yourself writing a description with branching logic ("if action is create, then...; if action is delete, then..."), that is usually a sign you should split it into separate tools with separate names and descriptions. This also makes error handling and permissioning per-action cleaner downstream.</p>
      <h2>Testing schemas like an interface, not an implementation detail</h2>
      <p>Because the schema is the only thing standing between a natural-language request and a correctly-formed function call, it deserves the same review rigor as a public API contract. Read the description as if you had never seen the underlying implementation and ask whether it alone would let you fill in every parameter correctly. A useful exercise is to hand the schema, with no other context, to a fresh model conversation along with a handful of realistic user requests and see whether the resulting <code>tool_use</code> input is what you would have written by hand. Mismatches point directly at where the description is underspecified. This kind of review also surfaces overloaded parameters — a single field silently expected to hold either an email or a username, for instance — that are easy to miss when you already know, from having written the backend, which one you meant.</p>
      <p>It also pays to think about how the description reads next to the descriptions of every other tool available in the same conversation. Two tools with similar-sounding descriptions but different side effects (one that previews a change, one that commits it) are a common source of the model picking the wrong one under time pressure. Make the distinguishing detail — read-only versus mutating, reversible versus not — explicit and early in the description text rather than buried at the end, since that is the detail most likely to disambiguate a close call between two similar tools.</p>
      <div class="callout"><b>Exam trap</b> A question describes a tool that the model keeps calling with the wrong arguments or fails to call when it should, and offers "rename the tool to something more descriptive" as an answer choice. That is usually the wrong fix. The correct diagnosis is almost always that the <code>description</code> field is vague or missing examples — renaming does far less than rewriting the description. Do not pick the naming answer when the description is the actual problem.</div>
      <blockquote>Scenario: a support-ticket tool takes a <code>status</code> string parameter with no further constraint. In production, the model sometimes sends "closed", sometimes "Closed", sometimes "resolved" — none of which match the backend's expected value of "CLOSED". The right fix is to add an <code>enum</code> listing the exact valid status strings in the schema, not to add a sentence to the description asking the model to "use the correct status format." Constraints the model can see in the schema are far more reliable than instructions it has to remember and infer correctly.</blockquote>
      <h2>Try it</h2>
      <p>Write a tool schema for a "cancel_subscription" action against a fictional billing API. Give it a required <code>subscription_id</code> string and an optional <code>reason</code> enum with three or four values. Deliberately write a bad, one-line description first, call it with a vague natural-language request, and see what arguments the model produces. Then rewrite the description with an explicit statement of when to call it, an example subscription_id format, and a note about what happens if the subscription is already canceled. Compare the two runs.</p>
    `
  },
  {
    slug: "2-2-tool-use-tool-result",
    title: "tool_use and tool_result in Practice",
    dek: "The mechanics of the tool_use and tool_result message loop, including error signaling and multi-turn ID matching.",
    minutes: 8,
    bodyHtml: `
      <p>Tool calling with the Claude API is a turn-based loop between your client code and the model, not a single API call. Understanding exactly which side produces which message type is a recurring exam point.</p>
      <h2>Who emits what</h2>
      <p>When the model decides to call a tool, it emits a <code>tool_use</code> content block inside its own assistant message. That block contains a <code>name</code> (the tool being called), an <code>id</code> (a unique identifier for this specific call), and <code>input</code> (the arguments, already validated against your schema's shape by the model's generation). The model does not execute anything — it only produces this block and stops generating (typically with <code>stop_reason: "tool_use"</code>).</p>
      <p>Execution is entirely your client's responsibility. Your code reads the <code>tool_use</code> block, runs the corresponding function or API call, and constructs a <code>tool_result</code> block. That block is sent back to the model inside a new user-role message, and its <code>tool_use_id</code> field must match the original <code>id</code> from the <code>tool_use</code> block it is answering. This id match is how the model correlates results with calls, which matters a lot when multiple tools are called in parallel in a single turn.</p>
      <h2>Multiple calls in one turn</h2>
      <p>A single assistant message can contain several <code>tool_use</code> blocks side by side, representing parallel tool calls the model wants executed. Your client should execute all of them (concurrently if safe) and then return a single user message containing one <code>tool_result</code> block per <code>tool_use_id</code>, all in that one message, before sending the next request. Sending results back one at a time across separate requests is not how the protocol is structured — the model expects all outstanding tool calls from a turn to be resolved together.</p>
      <h2>Signaling failure</h2>
      <p>When execution fails — the API times out, the input was semantically invalid even though it matched the schema, a downstream resource doesn't exist — the client sets <code>is_error: true</code> on the <code>tool_result</code> block and puts a clear, human-readable explanation in its content. This is not optional plumbing; it is the mechanism by which the model learns a call failed and can attempt a corrected retry in its next turn. Omitting <code>is_error</code> and just stuffing an error string into a normal-looking result can cause the model to treat a failure as a valid answer and hallucinate downstream conclusions from it.</p>
      <h2>The loop, end to end</h2>
      <p>Stepping back, a full tool-calling exchange looks like: your client sends a message with <code>tools</code> defined; the model responds with a <code>tool_use</code> block and <code>stop_reason: "tool_use"</code>; your client executes the tool and sends a new message containing a <code>tool_result</code>; the model reads that result and either produces a final text answer, or emits another <code>tool_use</code> block to keep working. This can chain for many turns — a research agent might call a search tool, then a fetch tool, then a summarization tool, each round trip adding one assistant tool_use message and one user tool_result message to the growing conversation. Nothing about the protocol caps how many rounds this goes on for; that's a limit your client code has to enforce itself, typically with a maximum iteration count or a timeout, since an unbounded loop is a real operational risk once tools are wired to production systems.</p>
      <p>Conversation history matters here too: every prior tool_use and tool_result block stays in context for subsequent turns unless you deliberately prune it, which is part of why long tool-calling sessions can consume tokens quickly. Some client implementations summarize or drop older tool_result content once it's no longer relevant to the current step, precisely to keep the transcript from growing unboundedly across a long agentic loop.</p>
      <div class="callout"><b>Exam trap</b> A question may ask "which component sends the tool_result block?" with "the model" as a tempting wrong answer, because tool_result blocks conceptually respond to something the model asked for. The model never sends tool_result — it only ever sends tool_use. The client (your application code) is always the one constructing and sending tool_result. Keep the direction fixed: tool_use flows model-to-client, tool_result flows client-to-model.</div>
      <blockquote>Scenario: the model emits two tool_use blocks in one turn — one calling a weather lookup, one calling a currency converter — because the user asked "what's the weather in Tokyo and what's 100 USD in yen." The weather call succeeds; the currency API times out. The correct client behavior is to return one user message containing two tool_result blocks: one normal result with the weather data, and one with is_error:true and a message like "currency conversion service timed out, try again" — both in the same message, matched by their respective tool_use_id values.</blockquote>
      <h2>Try it</h2>
      <p>Using the Claude API directly (not an SDK's agent loop), write a minimal script that defines one simple tool (for example, get_time with a timezone parameter), sends a message that triggers it, manually inspects the returned tool_use block's id, constructs a tool_result with a deliberately wrong tool_use_id, and sends it back. Observe how the API responds to the mismatched id, then fix it and confirm a matched id produces a normal continued response.</p>
    `
  },
  {
    slug: "2-3-mcp-fundamentals",
    title: "MCP Fundamentals: Servers, Clients, Hosts",
    dek: "The core MCP vocabulary — server, client, host — and how these three roles connect in a running system.",
    minutes: 7,
    bodyHtml: `
      <p>The Model Context Protocol (MCP) is an open protocol that standardizes how AI applications connect to external tools, data sources, and prompt templates. Before MCP, every integration between a model-powered app and, say, a database or a ticketing system was a bespoke, one-off integration. MCP defines a common wire protocol so that an integration written once as an MCP server can be used by any MCP-compatible application without custom glue code.</p>
      <h2>The three roles</h2>
      <p>MCP defines three distinct roles, and the exam is precise about which word means which role.</p>
      <ul>
        <li><strong>Server</strong>: the thing that exposes capabilities — tools, resources, and/or prompts — over the protocol. A server wraps some external system: a GitHub server exposes GitHub operations, a Postgres server exposes database queries, a filesystem server exposes file operations. The server owns the implementation details of talking to that external system.</li>
        <li><strong>Client</strong>: maintains a 1:1 connection to exactly one server. A client is not a general-purpose consumer of many servers at once — each client instance is scoped to a single server connection, handling that connection's session, capability negotiation, and message routing.</li>
        <li><strong>Host</strong>: the application the user actually interacts with — Claude Code, Claude Desktop, or a custom agent application. The host coordinates multiple clients simultaneously, one per connected server, and is what decides which servers to connect to, presents available tools to the model, and enforces permissioning around what the model is allowed to call.</li>
      </ul>
      <p>So a single host, like Claude Code, might run three clients concurrently, each one connected 1:1 to a different server (a GitHub server, a Postgres server, and a Slack server). The host aggregates what all three clients expose and presents a unified surface to the model and the user.</p>
      <h2>Why the 1:1 constraint matters</h2>
      <p>The client-per-server design keeps each connection's protocol state (capability negotiation, session lifecycle, subscriptions to resource updates) isolated and simple. It also means adding a new server to a host is additive — you spin up one more client — rather than requiring changes to how existing connections are managed.</p>
      <h2>Capability negotiation and lifecycle</h2>
      <p>When a client first connects to a server, the two sides perform a handshake in which the server advertises which primitives it supports — does it expose Tools, Resources, Prompts, some combination, or none — along with protocol version information. The host uses this to decide what to surface to the model and the user for that particular connection; a server that only exposes Resources, for instance, will never appear as a callable tool no matter how the model is prompted. This negotiation happens once per connection, at startup, not per-request, which is part of why the client is scoped to a single server: the negotiated state belongs to that one relationship and doesn't generalize across servers with different capabilities.</p>
      <p>It is also useful to keep the three roles distinct when reasoning about failure. If a server crashes, only the one client connected to it is affected — the host and its other clients keep functioning, and the host is responsible for deciding whether to surface that degraded state to the user (for example, showing that one server's tools are temporarily unavailable) rather than failing the whole session. That resilience story only works because responsibilities are partitioned the way they are: server owns the external system, client owns one connection's state, host owns orchestration across all of them.</p>
      <div class="callout"><b>Exam trap</b> Questions sometimes swap "client" and "host" in answer choices, betting that test-takers conflate "the application I use" with "the client." Remember: the application the user opens (Claude Code, Claude Desktop) is the host. The client is an internal component of the host, invisible to the end user, that manages one server connection. If an answer choice says "the client coordinates multiple server connections," that is describing the host's job, not the client's — it's wrong.</div>
      <blockquote>Scenario: a team wants Claude Code to be able to query their internal analytics database and also create Jira tickets. The correct architecture is one MCP server for the analytics database and a separate MCP server for Jira, with Claude Code (the host) running two clients, one per server. It would be architecturally wrong to try to build a single combined "analytics-and-jira" server just to avoid running two clients — servers should be scoped to one external system, and the host is designed to handle multiple clients without added complexity.</blockquote>
      <h2>Try it</h2>
      <p>In Claude Code, run the command to list configured MCP servers (check the CLI's MCP-related slash command or config file) and note how many servers are connected. For each one, identify what single external system it wraps. If you have none configured, add one lightweight server (a filesystem or fetch server is a common starting point) and observe how it appears as a distinct connection separate from any others you add later.</p>
    `
  },
  {
    slug: "2-4-mcp-primitives",
    title: "MCP Primitives: Tools, Resources, Prompts",
    dek: "The three MCP primitives, who invokes each one, and how to pick the right primitive for a given capability.",
    minutes: 8,
    bodyHtml: `
      <p>MCP servers expose capabilities through three distinct primitive types: Tools, Resources, and Prompts. These are not interchangeable — each is invoked by a different party in the system, and picking the wrong primitive for a capability produces an awkward or broken integration even if the underlying code works fine.</p>
      <h2>Tools: model-invoked actions</h2>
      <p>Tools are actions the model itself decides to invoke, the same way it would call any other tool_use-based function. A "create_ticket" or "run_query" capability belongs here. The model reads the tool's description and schema (exactly as covered in tool schema design) and autonomously decides, based on the conversation, whether and when to call it. Tools are for anything where the decision of "should this run right now" should be made by the model reasoning about the user's request.</p>
      <h2>Resources: contextual data the app reads</h2>
      <p>Resources are data the host application can read and attach as context — a file's contents, a database schema, a log excerpt, a configuration document. Critically, resources are typically surfaced and selected by the user or the host application, not autonomously invoked by the model the way tools are. A user might browse available resources in a UI and attach one to a conversation, or the host might attach a resource automatically based on the current working context (like the currently open file). The model then reads the resource's content as part of its context, but the model does not "call" a resource the way it calls a tool.</p>
      <h2>Prompts: reusable templates</h2>
      <p>Prompts are reusable, parameterized templates that a server exposes for constructing a well-formed conversation starter or a common workflow — for example a "review_pull_request" prompt that expands into a structured instruction set when a user selects it. Like resources, prompts are invoked by the user or the host's UI (often surfaced as a slash-command-like menu), not autonomously by the model. They exist to standardize a recurring interaction pattern the server author has already figured out is useful.</p>
      <h2>Choosing the right primitive</h2>
      <p>The deciding question is: who should decide when this capability activates? If the answer is "the model, reasoning in-context about what the user needs" — that's a tool. If the answer is "the user, browsing and picking what to attach" — that's a resource. If the answer is "the user, invoking a known named workflow" — that's a prompt.</p>
      <h2>Overlap and combinations</h2>
      <p>A single server commonly exposes more than one primitive type, and a capability that starts as one primitive can reasonably grow a second form as usage patterns become clear. A wiki server might begin with just a Tool for search-and-fetch, then later add specific Resources for a handful of documents that are attached in nearly every conversation, since forcing the model to search for the same onboarding page every single session is wasted latency and tokens compared to letting a user attach it once as a Resource. Similarly, a workflow that starts as informal instructions typed into chat each time is a good candidate to formalize into a Prompt once a team notices they're retyping the same structure repeatedly.</p>
      <p>The three primitives also differ in how much they rely on the model's judgment versus the host's UI. Tools depend entirely on description quality, exactly as covered for API-level tool schemas, because the model has no other signal for when to call them. Resources and Prompts depend more on how the host chooses to surface them — a host with a poor resource-browsing UI will make even well-designed Resources hard for users to find and attach, which is a host-side failure rather than a server-design failure.</p>
      <div class="callout"><b>Exam trap</b> A scenario describes read-only reference data, like a company's style guide or a product catalog, and the model needs it available. A common wrong answer is to expose this as a Tool the model "fetches" on demand. While that can technically work, the exam favors modeling clearly static, contextual, non-decision-driven data as a Resource rather than a Tool — the distinguishing signal in the question is usually phrasing like "the user selects which document to include" (Resource) versus "the model determines when it needs to look something up" (Tool). Watch for who is described as making the invocation decision.</div>
      <blockquote>Scenario: an MCP server for an internal wiki exposes the wiki's search-and-fetch-page capability as a Tool (the model decides when a question needs a wiki lookup), exposes a specific onboarding document as a Resource a new employee can manually attach to their first chat, and exposes a "draft_incident_report" Prompt that a user explicitly invokes to get a pre-structured template. Three different primitives, three different invokers, same server.</blockquote>
      <h2>Try it</h2>
      <p>Pick any MCP server you have configured (or a public one's documentation) and list every capability it exposes, sorting each into Tools, Resources, or Prompts. For at least one Tool, explain in a sentence why it makes sense for the model to decide when to invoke it rather than the user; for at least one Resource or Prompt, explain why user selection is the better fit than model autonomy.</p>
    `
  },
  {
    slug: "2-5-transport-choice",
    title: "Transport Choice: stdio vs. Streamable HTTP",
    dek: "When to use the stdio transport versus Streamable HTTP for an MCP server, based on trust boundary and deployment shape.",
    minutes: 7,
    bodyHtml: `
      <p>MCP defines the message format (JSON-RPC-based) separately from how those messages physically travel between client and server. That physical layer is the transport, and MCP supports two primary transports: stdio and Streamable HTTP. Choosing between them is a deployment decision, not a protocol-capability decision — both transports carry the same primitives (Tools, Resources, Prompts) equally well.</p>
      <h2>stdio: local, trusted subprocess</h2>
      <p>With the stdio transport, the host launches the MCP server as a local subprocess and communicates with it over that process's standard input and standard output streams. There is no network involved. This is the natural choice when the server runs on the same machine as the host, is trusted (often because you or your organization wrote it, or it's a well-known open-source server you installed locally), and doesn't need to be shared across multiple users or machines. A local filesystem server or a local git server are canonical stdio use cases — you want the server to have direct access to your local disk, and there's no reason to put a network hop in the way.</p>
      <p>stdio's simplicity is also its constraint: the server's lifecycle is tied to the host process that spawned it, and it can only serve the one host that launched it. It is not reachable by anyone else, on this machine or another.</p>
      <h2>Streamable HTTP: remote, shared</h2>
      <p>Streamable HTTP is the transport for servers that run independently of any one host — as a standalone deployed service, potentially serving many different hosts and users concurrently. This is the right choice when the server needs to be reachable over a network, when it wraps a resource that shouldn't have credentials distributed to every individual machine that wants to use it (better to centralize the credential in one deployed server), or when multiple team members or multiple applications should share one running server instance rather than each spinning up their own local copy. Streamable HTTP replaced the older HTTP+SSE transport and supports the same duplex streaming needs — server-initiated messages and long-running operations — over standard HTTP.</p>
      <h2>The deciding questions</h2>
      <p>Ask: does this server need to run on infrastructure separate from the host's machine? Do multiple people or hosts need to hit the same running instance? Is the resource being wrapped something you'd rather centralize credentials for, rather than distribute? A "yes" to any of these points toward Streamable HTTP. If the server is purely local tooling for one developer on one machine, stdio is simpler, has lower latency, and avoids standing up any hosting infrastructure at all.</p>
      <h2>Operational differences worth knowing</h2>
      <p>Beyond the trust and sharing question, the two transports have different operational profiles that scenario questions sometimes lean on. A stdio server's failure mode is local and contained — if it crashes, only the host process that spawned it is affected, and restarting the host typically respawns it. A Streamable HTTP server's failure mode looks like any other remote service outage: it can go down independently of any client, needs its own monitoring, and a network partition can leave a client unable to reach it even though both the host and the server process are individually healthy. Authentication is also asymmetric: a stdio subprocess inherits trust implicitly from having been launched by the host on the same machine, with no separate auth handshake typically required, while a Streamable HTTP server has to authenticate each client independently, since anyone who can reach it over the network is a potential caller. Designing that authentication layer is part of the cost of choosing Streamable HTTP, not an afterthought.</p>
      <div class="callout"><b>Exam trap</b> A question describes an MCP server that needs to be used by an entire team, each person running their own instance of the host application (Claude Code, Claude Desktop, etc.) on their own laptop, connecting to one shared company database. The trap answer is stdio, reasoning "it's simple and stdio is the default." But since multiple hosts on multiple machines need to reach the same server, and centralizing database credentials in one place is preferable to distributing them to every laptop, Streamable HTTP is correct here. Local-only convenience is not the deciding factor — shared, remote reachability is.</div>
      <blockquote>Scenario: a solo developer wants an MCP server that lets Claude Code read and write files in a specific project directory on their laptop. No sharing, no remote access, no credential-centralization concern — the server and host are always on the same machine. stdio is the right call: launch it as a subprocess, communicate over stdin/stdout, done. Reaching for Streamable HTTP here would mean standing up and securing a network-facing service for a capability that never needs to leave the machine.</blockquote>
      <h2>Try it</h2>
      <p>Look at the configuration for any stdio-based MCP server you have set up (the command and args used to launch it) and identify what would have to change to serve it over Streamable HTTP instead — specifically, what you would need to add for authentication, since a locally-spawned stdio process inherits trust from being launched by the host, while a network-reachable HTTP server cannot make that assumption.</p>
    `
  },
  {
    slug: "2-6-error-handling-distribution",
    title: "Error Handling and Tool Distribution Choices",
    dek: "How to design structured tool error responses and how to choose between a built-in tool, an MCP server, and a skill.",
    minutes: 8,
    bodyHtml: `
      <p>This lesson covers two related decisions that show up together on the exam: how a tool should report failure, and which mechanism — built-in tool, MCP server, or skill/slash command — should carry a given piece of functionality in the first place.</p>
      <h2>Structured error responses</h2>
      <p>When a tool call fails for any reason — invalid input that passed schema validation but failed at runtime, a downstream service being unavailable, a permission denial, a not-found condition — the response sent back to the model should always be a <code>tool_result</code> with <code>is_error: true</code> and a message describing what went wrong in plain, actionable language. This is what lets the model self-correct on the next turn: it can see that the call failed, understand roughly why, and either retry with adjusted input, try a different tool, or surface the problem to the user instead of confabulating a fake success.</p>
      <p>What that error message should never contain is a raw stack trace, a database error code with no explanation, or an internal exception string. Those are meaningless to the model as guidance and often leak implementation details (table names, internal paths, library versions) that shouldn't be exposed. The fix is to catch the underlying error in your tool implementation and translate it into a short, human-readable sentence describing what went wrong and, where possible, what a valid retry would look like — for example, "no customer found with id cus_004, check the id format" rather than "KeyError: 'cus_004' at db/lookup.py:52."</p>
      <div class="callout"><b>Exam trap</b> A question shows a tool implementation that, on failure, returns the full exception text (including file paths and a stack trace) inside a tool_result with is_error:true correctly set. Test-takers sometimes mark this fully correct because the is_error flag is present. But returning a raw stack trace as the error content is itself the flaw being tested — is_error:true is necessary but not sufficient; the content also has to be a clear, actionable message the model can act on. Both conditions must hold.</div>
      <h2>Choosing how to expose a capability</h2>
      <p>Given some piece of functionality you want an agent to have, there are three common ways to expose it, and the exam expects you to pick the right one for a given scenario rather than defaulting to MCP for everything:</p>
      <ul>
        <li><strong>Built-in tool</strong>: if a built-in tool already does what's needed — Bash, the text editor tool, web search, web fetch — use it rather than building a custom equivalent. Reimplementing "run a shell command" or "fetch a URL" as a custom MCP tool adds maintenance burden and duplicated surface area for no benefit over the tool Anthropic already ships and maintains.</li>
        <li><strong>MCP server</strong>: use this for integrations with an external system — a SaaS API, a database, a ticketing system — especially when that integration needs to be reused across multiple projects or multiple host applications. The value of MCP is standardizing that integration once so it's portable; if you'll only ever use it in one project and it involves no external system, MCP is more infrastructure than the problem needs.</li>
        <li><strong>Skill or slash command</strong>: use this for a project-local workflow that doesn't talk to any external system — packaging up a sequence of steps, a house style, or a repeatable procedure that's specific to one codebase or one team's way of working. There's no external system to integrate with, so standing up a server is unnecessary; a skill or slash command captures the workflow directly where it's used.</li>
      </ul>
      <div class="callout"><b>Exam trap</b> A scenario describes wanting to automate a purely local, repo-specific code review checklist with no external system involved, and offers "build an MCP server for it" as an answer choice. This is the over-engineering trap: MCP is for external-system integration, and a purely local, project-specific workflow with nothing external to talk to belongs in a skill or slash command, not a server. Don't reach for MCP just because the exam domain is about MCP — the correct answer is sometimes explicitly not MCP.</div>
      <blockquote>Scenario: a team wants their agent to (1) run repo-local lint-and-format checks before committing, (2) query their production Postgres database, and (3) fetch arbitrary web pages for research. The right distribution is: (1) a skill or slash command, since it's a local workflow with no external system; (2) an MCP server, since Postgres is an external system that multiple team members and projects will want to query the same way; (3) the built-in web fetch tool, since Claude already ships one and there's no reason to rebuild it.</blockquote>
      <h2>Try it</h2>
      <p>Take a tool you've built or are considering building. Write out its failure modes (bad input, downstream timeout, not-found, permission denied) and draft the exact is_error:true message text for each — not a category, the literal sentence the model would receive. Then separately classify the tool itself: should it actually be a custom tool at all, or does it duplicate a built-in, belong in an MCP server, or belong in a skill instead?</p>
    `
  }
];
