export const LESSONS = [
  {
    slug: "4-1-system-prompts",
    title: "System Prompts vs. User Messages",
    dek: "Where the role, constraints, and per-turn task belong, and why mixing them up causes drift in multi-turn conversations.",
    minutes: 7,
    bodyHtml: `
      <p>The Claude API separates a request into two channels: a top-level <code>system</code> parameter and the <code>messages</code> array. They are not interchangeable, and the exam tests whether you know which content belongs in which.</p>
      <h2>What each channel is for</h2>
      <p>The system prompt sets identity and standing instructions that apply for the entire conversation: the assistant's role, tone, output format defaults, safety constraints, tool-use policy, and anything that should hold true across every turn. It is set once per request and effectively persists as long as the conversation keeps sending it back.</p>
      <p>A user message carries the per-turn task: the specific question, the document to summarize, the code to review right now. It changes every turn. Content that is true for turn 3 but not turn 7 does not belong in the system prompt.</p>
      <h2>Why the distinction matters in practice</h2>
      <p>If you put per-turn specifics into the system prompt, you end up rebuilding the entire system prompt on every request just to swap one detail, which is wasteful and error-prone, and it also means that detail applies to the whole conversation history even though it was only relevant to one exchange. Conversely, if you put role and constraint information into a user message, later turns may drift away from it, because the model treats it as one data point in the conversation rather than a standing rule.</p>
      <p>A useful test: if the instruction would still be true on turn 50 of the same conversation, it belongs in the system prompt. If it is only true for this one exchange, it belongs in the user message.</p>
      <div class="callout"><b>Exam trap</b> A question describes a chatbot where the system prompt is rebuilt on every single turn to include that turn's user-specific data (e.g., "the user's account ID is 4471, answer their question about billing"). The correct fix is to move the account ID and the question into the user message and keep the system prompt static across turns. Expect a distractor answer that says "add more instructions to the system prompt" — that does not address the actual problem, which is channel misuse, not insufficient instruction.</div>
      <blockquote>A support tool sends a fresh system prompt on every API call containing: the assistant's role ("You are a support agent for Acme Cloud"), tone rules, escalation policy, and also the current ticket's subject line and the customer's last message. Each turn, the ticket subject and customer message change, so the system prompt is regenerated in full every time, and the message history grows without ever reusing a stable system prompt. The fix: keep the system prompt fixed to role, tone, and policy only; move ticket subject and customer message into the user message for that turn. This also allows prompt caching to work correctly, since the system prompt no longer changes between calls.</blockquote>
      <h2>System prompts and prompt caching</h2>
      <p>Because the system prompt is meant to stay stable across a conversation, it is also the natural place to put large, reusable content you want cached: long role descriptions, static reference material, extensive formatting rules. If you instead scatter that content across user messages, or regenerate it slightly differently every turn, you lose the ability to reuse a cached prefix, and you pay to reprocess the same tokens repeatedly. Keeping the system prompt byte-for-byte identical across calls (aside from occasional updates) is both a design-clarity practice and a cost optimization.</p>
      <h2>Multiple system-style instructions in one conversation</h2>
      <p>A related mistake is trying to change the assistant's standing behavior mid-conversation by injecting a new "system-like" instruction into a user message ("from now on, only answer in Spanish"). This can work, but it is fragile — the instruction now competes with the original system prompt and with the rest of the conversation history, and its effect can fade over many subsequent turns. If a behavior change is meant to be durable, the more reliable approach is to update the actual system prompt on the next request, not to bury a new standing rule inside a user turn.</p>
      <h2>Try it</h2>
      <p>Take a prompt you currently send with a single long user message that mixes "you are an expert X" framing with the actual task. Split it: move the role/format/constraint sentences into <code>system</code>, leave only the task-specific content in the user message. Send both versions for three different task inputs and compare whether the split version keeps the format constraint (e.g., "always answer in three bullet points") more consistently across all three. Then run the split version twice with an identical system prompt and check whether your client library reports a cache hit on the second call.</p>
    `
  },
  {
    slug: "4-2-xml-few-shot",
    title: "XML Structuring and Few-Shot Prompting",
    dek: "Using XML-like tags to separate prompt components and using worked examples to pin down exact output format.",
    minutes: 8,
    bodyHtml: `
      <p>Two closely related but distinct techniques show up constantly on the exam: wrapping prompt components in XML-like tags, and giving the model worked examples (few-shot prompting). They solve different problems and are often used together.</p>
      <h2>XML structuring</h2>
      <p>When a prompt mixes several kinds of content — instructions, background context, reference documents, examples, the actual question — the model has to infer where one section ends and another begins. Wrapping each component in tags such as <code>&lt;instructions&gt;</code>, <code>&lt;context&gt;</code>, <code>&lt;document&gt;</code>, or <code>&lt;examples&gt;</code> removes that ambiguity. The tags do not need to follow a formal schema; they just need to be consistent and used with a closing tag that matches the opening tag.</p>
      <p>This matters most for long prompts, not short ones. A two-sentence prompt with one instruction does not benefit from tagging. A prompt that includes a 2,000-word reference document, a set of formatting rules, and three examples benefits a lot, because without tags the model may conflate the example text with the actual task input, or treat part of the reference document as an instruction.</p>
      <h2>Few-shot prompting</h2>
      <p>Few-shot prompting means including 2-5 worked input/output pairs that demonstrate the exact pattern you want, rather than describing that pattern in prose. It is the right tool when the desired output has a precise shape that is hard to specify in words: a particular JSON key ordering, a specific tone and length, a formatting convention like how to cite sources or how to abbreviate units. Instructions alone tend to under-specify these details; examples remove the ambiguity directly.</p>
      <p>Few-shot and XML structuring combine naturally: wrap each example pair in its own <code>&lt;example&gt;</code> tags, with nested <code>&lt;input&gt;</code> and <code>&lt;output&gt;</code> tags, so the model can clearly tell where one example ends and the next begins, and can distinguish the examples block from the real task at the end of the prompt.</p>
      <div class="callout"><b>Exam trap</b> A question presents a failing extraction prompt that already has clear, well-written prose instructions describing the desired JSON format, but the model keeps producing slightly wrong field names or ordering. The tempting wrong answer is "add more detailed instructions explaining the format." The correct answer is to add 2-3 few-shot examples instead — the problem is that the desired pattern is precise and hard to fully specify in prose, which is exactly the case few-shot solves better than more instructions.</div>
      <blockquote>A prompt asks Claude to convert freeform customer complaints into a structured triage note with fields for severity, category, and a one-line summary written in a specific terse style ("Customer unable to log in after password reset; sev 2"). Prose instructions describing "terse, sev-N style" produce inconsistent phrasing across calls. Adding three examples of complaint-to-triage-note pairs, each wrapped in <code>&lt;example&gt;</code> tags, fixes the inconsistency because the exact phrasing convention is something the model can copy from examples far more reliably than it can infer from a description of "terse style."</blockquote>
      <h2>Choosing tag names and nesting</h2>
      <p>There is no reserved or required tag vocabulary — <code>&lt;context&gt;</code>, <code>&lt;background&gt;</code>, and <code>&lt;reference_material&gt;</code> are all equally valid choices, as long as you are consistent within a prompt and the opening and closing tags match. What matters is that each distinct kind of content gets its own tag, and that the actual task or question is clearly set apart from the supporting material, typically placed last and wrapped in something like <code>&lt;task&gt;</code> so the model knows where instructions end and the live request begins. Nesting is fine and often useful: a <code>&lt;examples&gt;</code> block containing several <code>&lt;example&gt;</code> children, each with its own <code>&lt;input&gt;</code> and <code>&lt;output&gt;</code>, is a common and reliable structure.</p>
      <h2>How many examples, and how to choose them</h2>
      <p>Two to five examples is the typical range. Fewer than two does not really establish a pattern; beyond five, returns diminish quickly and you are mostly spending tokens. Example selection matters more than example count: examples should cover the edge cases you actually care about, not just the easy, typical case repeated with different wording. If the real task includes some inputs that are ambiguous or unusual, include at least one example that shows the desired behavior on that kind of input, since the model will generalize from whatever pattern the examples actually demonstrate — including edge-case handling if you show it, or ignoring edge cases if you don't.</p>
      <h2>When XML tagging is unnecessary overhead</h2>
      <p>For a short, single-purpose prompt with one instruction and one piece of input text, adding tags is not wrong but adds no measurable benefit, and the exam sometimes uses this to test whether you over-apply techniques. The signal to reach for tagging is prompt complexity — multiple distinct content types coexisting in one prompt — not prompt length alone.</p>
      <h2>Try it</h2>
      <p>Pick a task where you currently only describe the output format in prose (for example, extracting structured fields from freeform text). Send it once with prose instructions only, then again with the same instructions plus 3 few-shot examples wrapped in <code>&lt;example&gt;</code> tags, including at least one edge-case example. Run each version against 5 different inputs, including one deliberately tricky one, and count how often the output format deviates in each case.</p>
    `
  },
  {
    slug: "4-3-chain-of-thought",
    title: "Chain-of-Thought: When It Helps",
    dek: "When asking Claude to reason step by step improves accuracy, and when it just adds latency and cost for no benefit.",
    minutes: 7,
    bodyHtml: `
      <p>Chain-of-thought (CoT) prompting asks the model to work through its reasoning step by step before producing a final answer, instead of jumping straight to the answer. The exam tests whether you can identify when this is worth the cost, because it is not free.</p>
      <h2>The tradeoff</h2>
      <p>CoT reliably improves accuracy on tasks that require multiple dependent reasoning steps: multi-step arithmetic, logic problems with several constraints, tasks that require weighing multiple pieces of evidence before concluding, or debugging where the cause has to be traced through several layers. Working through the steps explicitly reduces the chance the model skips a step or jumps to a plausible-sounding but wrong conclusion.</p>
      <p>The cost is real: reasoning text adds tokens, which adds latency and adds spend. For a simple lookup, a classification into one of a few clear categories, or a direct extraction task, there is no chain of dependent steps to walk through, so CoT adds cost without adding accuracy. Reserve it for genuinely multi-step problems, not routine tasks that just happen to sound complicated.</p>
      <h2>How to structure it</h2>
      <p>The most reliable pattern is to ask for reasoning in a clearly delimited block (for example inside <code>&lt;thinking&gt;</code> tags) followed by a clearly delimited final answer (for example inside <code>&lt;answer&gt;</code> tags), so downstream code can strip the reasoning and use only the final answer. Asking for reasoning "somewhere in the response" without structure makes it harder to parse out the actual answer programmatically.</p>
      <p>Note also that Claude models with extended thinking are a distinct mechanism from prompted chain-of-thought — extended thinking is a model-level feature you enable via API parameters, while prompted CoT is a prompting technique you can use with any model, including ones without a thinking mode. The exam may ask you to distinguish "ask the model to think step by step in the prompt" from "enable a dedicated reasoning mode" as two different tools for a similar goal.</p>
      <div class="callout"><b>Exam trap</b> A scenario describes a simple sentiment classification task (positive/negative/neutral) that is running slowly and expensively because every prompt includes "think step by step before answering." The correct fix is to remove the CoT instruction, since single-label classification from clear text is not a multi-step reasoning task and gains nothing from it. A wrong answer choice will suggest keeping CoT but "optimizing" it in some other way — the actual issue is that CoT is the wrong tool for this task at all, not that it's misconfigured.</div>
      <blockquote>A finance team asks Claude to determine whether a transaction violates a multi-clause compliance policy, where the policy has five interacting conditions (amount thresholds, counterparty type, jurisdiction, prior flags, and an exception clause). A direct answer without reasoning is frequently wrong because the model conflates two of the conditions or misses the exception clause. Asking for step-by-step reasoning through each clause before stating a verdict raises accuracy substantially, because this is exactly the multi-step, multi-constraint reasoning case CoT is built for, and the added latency is acceptable since this runs asynchronously, not in a live user-facing chat.</blockquote>
      <h2>Batch workloads and latency tolerance</h2>
      <p>The latency cost of chain-of-thought matters most in interactive, user-facing contexts where someone is waiting on a response. For large, non-interactive workloads — classifying a backlog of 50,000 support tickets, scoring a dataset overnight — latency per request is far less important than throughput and cost, and this is also the scenario where the async Batches API is the right infrastructure choice regardless of whether CoT is used, since it is built for large non-interactive jobs where waiting for results is acceptable. A scenario that combines "large offline batch job" with "task requires multi-step reasoning" can reasonably use CoT precisely because the usual latency objection doesn't apply.</p>
      <h2>CoT is not a substitute for a better task decomposition</h2>
      <p>Sometimes a task that appears to need chain-of-thought reasoning inside a single call is actually better solved by splitting it into separate calls — for example, a call that extracts relevant facts, followed by a call that reasons over just those facts. This is different from prompted CoT, which keeps everything in one call and asks the model to narrate its reasoning inline. Both can raise accuracy on genuinely multi-step problems; which one is preferable depends on whether the intermediate steps benefit from being independently inspectable, validated, or cached, in which case splitting into separate calls is usually the stronger design.</p>
      <h2>Try it</h2>
      <p>Take a task you currently run with "think step by step" prepended and check whether it is truly multi-step. If it is a single-step classification or lookup, strip the CoT instruction, run 10 identical inputs both ways, and compare both accuracy and response latency/token count between the two versions. Then take a genuinely multi-step task you run without CoT today, add a structured "reason inside &lt;thinking&gt; tags, then answer inside &lt;answer&gt; tags" instruction, and check whether accuracy improves enough to justify the added latency.</p>
    `
  },
  {
    slug: "4-4-prefill-structured-output",
    title: "Prefill and Guaranteed Structured Output",
    dek: "Seeding the start of Claude's response to force format, and the difference between asking for JSON and actually constraining it.",
    minutes: 8,
    bodyHtml: `
      <p>Two mechanisms let you control response format at the API level rather than relying on the model to follow prose instructions: prefill and structured/constrained output. The exam distinguishes them clearly, and conflating them is a common mistake.</p>
      <h2>Prefill</h2>
      <p>Prefill means you supply the beginning of the assistant's response yourself, in the <code>messages</code> array, as an assistant-role message with partial content, and the model continues from there. A common use is starting the assistant turn with a literal <code>{</code> so the model has no room to add a conversational preamble like "Sure, here's the JSON you requested:" before the actual object. This is a cheap, low-effort way to eliminate an entire class of formatting failures (preamble text, markdown code fences around JSON, apologetic hedging) without adding any instructions or examples.</p>
      <p>Prefill nudges the model toward a format; it does not enforce a schema. The model can still prefill-continue into malformed or incomplete JSON, wrong field names, or the wrong data types. It reduces one specific failure mode (extra text around the payload) but is not validation.</p>
      <h2>Actually constraining output vs. asking nicely</h2>
      <p>"Ask nicely for JSON" means putting instructions in the prompt like "respond only with valid JSON matching this schema" — this relies entirely on the model's compliance and can fail, especially under edge-case inputs. Actually constraining output means using a mechanism, such as a tool/function-call definition with a strict input schema, or a structured-output feature, where the response is generated to conform to a schema rather than merely asked to. Downstream code parsing model output should be built assuming "asked nicely" can fail; a genuinely constrained schema is far more reliable for code that cannot tolerate a parse error.</p>
      <p>A common real pattern: define a tool with a JSON schema for the exact fields you want, and force the model to call that tool, even though you have no intention of "executing" anything — the tool-call mechanism itself is being used purely to get schema-conformant output.</p>
      <div class="callout"><b>Exam trap</b> A question shows a prompt with the instruction "return only valid JSON, no other text" and asks why production code still occasionally throws a JSON parse error. The trap answer is "the instruction should be reworded to be more forceful." The correct diagnosis is that a prose instruction is being relied upon as if it were a guarantee — the fix is to move to an actual schema-constraining mechanism (tool-call schema) and/or add prefill, and code should also validate before trusting the output regardless.</div>
      <blockquote>A pipeline extracts structured line items from invoices and feeds them directly into an accounting system with no human review. The team is currently prompting "respond with a JSON array of objects with fields item, quantity, price" and parsing the raw text response. Occasional malformed responses break the pipeline. The correct fix is to define a tool with a strict schema for the line-item array and force a tool call, rather than continuing to refine the prose instruction — because this is a non-interactive, unattended path where a parse failure has real downstream cost, so relying on the model to voluntarily comply with a text instruction is the wrong tradeoff.</blockquote>
      <h2>Prefill beyond JSON</h2>
      <p>Prefill is not limited to forcing JSON. It also works for forcing a specific opening structure in free text — for example, prefilling "Verdict: " to force the model to lead with a classification before any explanation, or prefilling the first line of a multi-section report to lock in the section header format. The underlying mechanism is the same in every case: whatever text you supply becomes the literal start of the assistant's response, so the model has no opportunity to deviate from it, only to continue from it.</p>
      <h2>Combining prefill with schema constraints</h2>
      <p>Prefill and schema-constrained output are not competing choices — they stack. Forcing a tool call gets you a response shaped by a schema; prefill (where applicable to the surrounding response) removes any remaining preamble around it. On the exam, watch for scenarios that ask you to pick "the one best fix" when the real answer is that these techniques address different failure modes and are commonly used together rather than as alternatives to choose between.</p>
      <h2>Structured output still needs downstream validation</h2>
      <p>Even a strict schema only constrains shape and type — it typically cannot express business-rule constraints like "end_date must be after start_date" or "discount must not exceed the customer's tier limit." A response can satisfy the schema perfectly and still be wrong in a way that matters to your application. Structured output reduces parsing failures; it does not eliminate the need for application-level validation, which is the subject of the next lesson.</p>
      <h2>Try it</h2>
      <p>Take a prompt where you currently ask for JSON in prose. Run 10 varied inputs against it and count parse failures or preamble text. Then run the same 10 inputs with the assistant turn prefilled with a bare <code>{</code>, and separately with a tool-call schema forcing structured output. Compare failure rates across all three approaches, and note which failures each fix does and does not address.</p>
    `
  },
  {
    slug: "4-5-validation-retry",
    title: "Validation and Retry Loops",
    dek: "Programmatically validating structured output against a schema and re-prompting with the specific error, not a generic retry.",
    minutes: 8,
    bodyHtml: `
      <p>Even with prefill and schema-constrained output, structured responses can still fail validation: a required field missing, a value out of range, a type mismatch after JSON parsing succeeds. Validation/retry loops handle this failure mode programmatically instead of hoping the first response is correct.</p>
      <h2>The pattern</h2>
      <p>The loop is: generate a response, validate it against the schema (or business rules) in code, and if validation fails, send a new request that includes the specific validation error and asks the model to correct it — not just "try again." A generic retry with no information about what was wrong tends to reproduce the same mistake, because nothing about the input or the model's reasoning has changed; the model has no new information to act on. Including the exact validator error (for example, "field 'severity' must be one of low/medium/high, got 'urgent'") gives the model something concrete to fix, and works far more reliably.</p>
      <p>A well-built loop also caps the number of retries (commonly 2-3) and has a defined fallback path when validation keeps failing — surfacing to a human, logging for review, or falling back to a safer default — rather than retrying indefinitely.</p>
      <h2>Where this fits with other techniques</h2>
      <p>Validation/retry is not a replacement for schema-constrained output or prefill; it is a second layer on top of them. Constrained output and prefill reduce the rate of malformed responses; validation/retry catches the ones that still get through, including cases where the JSON is syntactically valid but semantically wrong (a number out of a valid range, an enum value that doesn't exist, a date in the past for a field that must be in the future). Schema constraints alone typically cannot express those business-rule-level constraints, so code-level validation is still required even with a perfect schema mechanism.</p>
      <div class="callout"><b>Exam trap</b> A scenario shows a retry loop where, on validation failure, the code simply re-sends the exact same prompt again (sometimes with a slightly higher temperature, hoping for a different sample). This is presented as a fix for occasional malformed output. The correct critique: this is a generic retry with no error feedback, and while it may occasionally succeed by chance, it does not reliably converge, especially if the mistake is systematic (e.g., the model consistently misunderstands a field's constraint). The right fix is to include the specific validation error text in the retry prompt.</div>
      <blockquote>An API integration asks Claude to produce a JSON object with a <code>discount_percent</code> field that must be between 0 and 50. On one run the model returns 75. A generic retry ("please try again, make sure the output is valid") has no guarantee of avoiding the same value or a similarly out-of-range one. The correct approach: the validator catches the range violation, and the retry prompt explicitly states "discount_percent must be between 0 and 50; you returned 75, which is out of range — provide a corrected value." This directly tells the model what was wrong and what constraint to satisfy, which converges far more reliably than an unspecific retry.</blockquote>
      <h2>Where to put retry logic in the message history</h2>
      <p>A retry is a new turn in the conversation, not a replacement of the previous one: the failed assistant response and the validation error both get appended as additional messages (assistant turn with the bad output, user turn with the specific error and a request to correct it), and the corrected response comes back as the next assistant turn. This preserves full context for debugging and lets the model see its own prior attempt alongside the correction, which is generally more effective than silently discarding the failed attempt and re-asking from scratch with no memory of what went wrong.</p>
      <h2>Retry loops and cost</h2>
      <p>Every retry is a full additional API call, so a validation/retry loop is not free, and an exam scenario may ask you to weigh it against the alternative of investing more in the initial prompt (better schema, more few-shot examples, prefill) to reduce how often retries are needed in the first place. The two are complementary, not competing: a well-designed initial prompt lowers the retry rate, and the retry loop exists to catch the remaining tail of failures, particularly ones caused by ambiguous or unusual inputs where no amount of upfront example curation covers every edge case.</p>
      <h2>Retry loops vs. multi-pass review</h2>
      <p>Don't confuse a validation/retry loop with a multi-pass review setup. A retry loop reacts to an objective, programmatic failure (schema violation, out-of-range value) and asks for a targeted correction. Multi-pass review is a separate, independent evaluation of otherwise valid output, checking for qualities a schema can't check — tone, correctness of reasoning, completeness — using a second call rather than code-level validation. A single system can reasonably use both: validate structurally with a retry loop, then send passing output through a separate review call for qualitative checks.</p>
      <h2>Try it</h2>
      <p>Build a small validation/retry loop around a structured-output call: define a schema with at least one business-rule constraint a JSON schema can't express (e.g., a numeric range or a cross-field consistency rule), validate the response in code, and on failure re-prompt including the exact validator error message as a new user turn appended after the failed assistant turn. Compare convergence rate against a version that just resends the same prompt on failure, over 10 forced-failure test cases, and cap both at 3 retries with a logged fallback on exhaustion.</p>
    `
  },
  {
    slug: "4-6-prompt-anti-patterns",
    title: "Common Prompt Anti-Patterns",
    dek: "Recognizable prompt design mistakes the exam tests: negative-only instructions, task overload, and self-review in one call.",
    minutes: 7,
    bodyHtml: `
      <p>This lesson collects recurring prompt-design mistakes that show up across exam scenarios. Recognizing the pattern by name is often faster than re-deriving the fix from first principles during the exam.</p>
      <h2>Negative-only instructions</h2>
      <p>Telling the model what not to do ("don't include a preamble," "don't use markdown," "don't mention pricing") without stating the positive alternative leaves the model to guess what to do instead, which produces inconsistent results. "Don't use markdown" is weaker than "respond in plain prose sentences, no headers or bullet lists." The fix is always to pair or replace the negative instruction with a concrete positive instruction describing the desired behavior directly.</p>
      <h2>Overloaded prompts</h2>
      <p>A single prompt asking the model to do several unrelated things at once — summarize a document, translate it, extract structured data from it, and critique its tone — tends to produce weaker results on each sub-task than separate, focused prompts would. This is different from a genuinely multi-step task where the steps depend on each other (which chain-of-thought or a structured multi-part prompt can handle well); the anti-pattern specifically refers to bundling unrelated tasks that don't need to share context, purely to save API calls. The fix is to split unrelated tasks into separate calls, each with a focused, single-purpose prompt.</p>
      <h2>Self-review in one call</h2>
      <p>Asking a single call to generate an answer and then check its own work in the same turn tends to rubber-stamp the generation, because the same reasoning that produced the (possibly flawed) answer is what's being asked to evaluate it — there's no independent perspective. The fix is a multi-pass review: a separate call, ideally with a differently framed prompt (and sometimes a different persona or explicit adversarial framing, "find problems with this output"), reviewing the first call's output. Separating generation and review into different calls produces meaningfully more critical review than asking one call to do both.</p>
      <h2>Other patterns worth knowing</h2>
      <p>Vague success criteria (asking for "a good summary" instead of specifying length, audience, and what to include/exclude) forces the model to guess at implicit requirements. Burying the actual task deep inside a long block of unstructured context, with no XML tags separating instructions from reference material, makes it easy for the model to lose track of what's actually being asked. Both are instances of the same underlying problem: leaving too much for the model to infer when it could be stated directly.</p>
      <div class="callout"><b>Exam trap</b> A scenario shows a single prompt asking Claude to draft a customer email, then evaluate whether the email is polite enough, then revise it if not, all in one response. The setup looks like it's already doing "review," so a tempting wrong answer is "this is fine, it already includes a review step." The correct critique is that self-review inside one generation call is unreliable — the fix is a second, separate call whose only job is to critique the first call's draft against explicit criteria.</div>
      <blockquote>A content pipeline prompt reads: "Write a product description. Don't make it sound salesy. Don't use exclamation points. Don't be too long." The output is inconsistent in tone across runs. The fix is to replace each negative constraint with a positive one: state the target tone directly ("write in a neutral, factual tone"), state a concrete length ("2-3 sentences"), and state what punctuation to use instead of only what to avoid. Positive, concrete instructions give the model a target to hit rather than an open-ended space of things to avoid.</blockquote>
      <h2>Anti-patterns as a checklist</h2>
      <p>On the exam, scenario questions about a failing or unreliable prompt are frequently solvable by pattern-matching against this list rather than reasoning from scratch: check whether the prompt states positive requirements or only prohibitions, whether it bundles unrelated tasks that could be split, whether it asks one call to both generate and critique itself, whether success criteria are vague, and whether distinct content types are separated with structure. Most "why is this prompt unreliable" questions map cleanly onto one of these five patterns, and the fix is almost always to state something explicitly that was previously left implicit.</p>
      <h2>Anti-patterns compound</h2>
      <p>These issues are not mutually exclusive, and a single weak prompt often exhibits several at once: a prompt with vague success criteria, no positive framing, and several unrelated tasks bundled together is common in practice, and fixing only one of the three issues may not measurably improve reliability. When a scenario's prompt is described as "unreliable" without further detail, it's worth checking it against the full list rather than assuming only one issue is present.</p>
      <h2>Try it</h2>
      <p>Take a prompt you have that contains at least one "don't do X" instruction with no stated alternative. Rewrite it as a positive instruction describing the desired behavior directly, run both versions against 5 inputs, and check whether the rewritten version produces more consistent output on the dimension the instruction was targeting. While you're at it, check the same prompt against the other four anti-patterns in this lesson and note which, if any, also apply.</p>
    `
  }
];
