export const LESSONS = [
  {
    slug: "5-1-context-windows-budgeting",
    title: "Context Windows and Token Budgeting",
    dek: "The context window is a shared, finite budget for input and output tokens, not just the visible chat text.",
    minutes: 7,
    bodyHtml: `
      <p>Every request to the Claude API operates inside a single finite budget: the context window. That budget is not "how much chat history fits on screen." It is the total token count across the <code>system</code> prompt, every tool definition you register, any retrieved documents or file contents you inject, the full conversation history, and the model's own output. All of it draws from the same pool. If you treat the context window as if it only holds user-visible messages, you will blow the budget in production long before you'd expect to, because tool schemas and retrieved context are frequently the largest consumers, not the dialogue itself.</p>
      <h2>What actually eats the budget</h2>
      <p>In a typical agentic system, the ranking of token consumers is often counterintuitive. A verbose <code>system</code> prompt with embedded few-shot examples can run several thousand tokens before a single user message arrives. Tool definitions compound this: each tool's name, description, and JSON schema for parameters costs tokens, and that cost is paid on <strong>every single request</strong> in the conversation, not once. An agent wired up with fifteen tools, each with a moderately detailed schema, can spend a meaningful fraction of a small context window before the model has read a single word from the user.</p>
      <p>Retrieved data is the other major line item. A naive RAG pipeline that stuffs five full documents into context because a search returned five hits will exhaust budget fast, and it does so silently until the request fails or the model starts truncating its own reasoning to compensate. Budgeting is a design activity, not an afterthought: you have to account for system prompt tokens, tool schema tokens, expected retrieval tokens, expected history tokens, and reserved output tokens as separate line items that sum to less than the model's context window, with margin left over.</p>
      <h2>Output tokens count against the same budget</h2>
      <p>Because the context window is shared between input and output, a request that fills 95% of the window with input leaves almost no room for the model to respond, especially for tasks that require long-form output like generating a large code diff or a detailed report. Reliable systems reserve output budget explicitly rather than discovering the shortfall when a response gets cut off mid-sentence.</p>
      <h3>Targeted retrieval over reflexive whole-file reads</h3>
      <p>This budgeting discipline extends directly into codebase exploration. An agent given access to a large repository should not reflexively read entire files, let alone entire directories, when it needs one function signature or one config value. A targeted grep or search that narrows to the relevant lines costs a fraction of the tokens that a full-file read costs, and it leaves budget for everything else the agent needs to reason about. This is one of the most commonly tested judgment calls on the exam: given a scenario where an agent needs to find how a specific function is used across a codebase, the correct answer is almost always "search first, read narrowly," not "read the whole repository into context and then reason over it."</p>
      <div class="callout"><b>Exam trap</b> A question describes an agent that "reads the entire file to be safe" before making a one-line edit, and asks whether this is good practice. The trap answer treats this as reasonable caution. The correct answer is that this wastes context budget for no proportional gain in correctness — targeted reads (grep for the function, read the surrounding 20 lines) achieve the same safety with a fraction of the token cost. Don't be swayed by framing that equates "reading more" with "being careful."</div>
      <blockquote>Scenario: An agent has a 200K-token context window, a system prompt of 3K tokens, twelve tool definitions totaling 4K tokens, and needs to reserve 8K tokens for output. A user request triggers a search that could return either three short snippets (600 tokens total) or the two full source files those snippets came from (22K tokens total). Which should the agent use, and why? The correct call is the snippets. The remaining budget after fixed costs is roughly 185K tokens, which sounds ample, but conversation history accumulates across turns, and burning 22K tokens on a single retrieval when 600 tokens would answer the question compounds badly over a multi-turn session. Budgeting is about the trajectory of usage across the whole conversation, not just whether a single request technically fits.</blockquote>
      <h2>Try it</h2>
      <p>Take a real system prompt and tool set you use (or a sample one), and actually count the tokens in the system prompt plus all tool definitions using the Anthropic token counting endpoint or a local tokenizer. Compare that fixed cost against the model's total context window as a percentage. If it's over 10-15% before any conversation happens, identify which tool descriptions or system prompt sections could be trimmed or made conditional.</p>
    `
  },
  {
    slug: "5-2-prompt-caching",
    title: "Prompt Caching Mechanics",
    dek: "Prompt caching reuses a stable prefix server-side, but only the content before the first change stays cacheable.",
    minutes: 7,
    bodyHtml: `
      <p>Prompt caching lets you mark a portion of your request as a reusable prefix so that, on subsequent requests, the model provider can skip reprocessing that prefix from scratch and instead read it from a server-side cache. This cuts both latency and cost on the cached portion, which matters enormously for agentic systems that send large, mostly-static context (system prompts, tool definitions, long documents) on every single turn of a conversation.</p>
      <h2>The prefix rule</h2>
      <p>The mechanic that matters most for the exam is this: caching works on a <strong>prefix</strong> basis. Everything up to and including your cache breakpoint is a candidate for reuse, but only if the bytes in that region are byte-for-byte identical to a previous request. The moment content changes anywhere before your cache boundary, the cache is invalidated for everything from that change point onward, even if 95% of the prefix is unchanged. This is why the ordering of content within a request is not a stylistic choice; it is the single largest lever you have over your cache hit rate.</p>
      <p>The practical consequence is that you must design your requests so that stable content comes first and variable content comes last. A system prompt, tool definitions, and any large static reference documents belong at the front of the request, marked with a cache breakpoint. Conversation history that grows turn by turn should be appended after that breakpoint. If you instead prepend new information, inject a timestamp into the system prompt, or reorder tool definitions between requests, you silently break caching for the entire prefix that follows, and you will not necessarily get an error, just a much higher bill and higher latency than expected.</p>
      <h2>Where this goes wrong in agent loops</h2>
      <p>A common mistake is including something trivially dynamic inside the cached region: a "current date" field, a random request ID, or a live token count injected into the system prompt on every call. Any one of these changes the prefix on every request and defeats caching entirely, even though the bulk of the system prompt is identical every time. The fix is to move genuinely dynamic content out of the cached prefix and into the part of the request that comes after the cache breakpoint, or to accept that highly dynamic fields cannot be cached and isolate their cost.</p>
      <p>Another failure mode is in multi-turn agent conversations where each turn's tool results get inserted in the middle of the history rather than appended at the end. If your framework reorders or summarizes earlier turns before the current one is sent, you invalidate the cache for the entire conversation on every single turn, which is exactly the scenario prompt caching is meant to optimize away.</p>
      <div class="callout"><b>Exam trap</b> A question presents a system prompt that begins with "Today's date is [dynamic date], you are a helpful assistant..." followed by a long, otherwise-static block of instructions and tool definitions, and asks why cache hit rates are low despite the prompt "mostly staying the same." The trap answer blames the model or the tool definitions. The correct diagnosis is that the dynamic date sits before the cache breakpoint (or at the very start of the prefix), invalidating the cache on every request regardless of how much of the rest is identical. The fix is moving dynamic fields after the cached block, not shortening the prompt.</div>
      <blockquote>Scenario: A support agent sends a request each turn containing: a 2,000-token system prompt, 1,500 tokens of tool definitions, a growing conversation history, and the current user message. The team notices cache hit rates are near zero even though the system prompt and tools never change. Investigation shows the conversation history is being summarized and reinserted near the top of the message list on every turn, ahead of the cache breakpoint, to "keep things tidy." The reasoning error: summarization is useful, but placing its output before the cache boundary — or restructuring anything before that boundary — invalidates the cache for the system prompt and tools that follow, even though those parts are unchanged. The fix is to place the cache breakpoint after the system prompt and tool definitions, and to only ever append new content afterward, keeping any summarization strictly downstream of the cached region.</blockquote>
      <h2>Try it</h2>
      <p>Send the same multi-turn conversation twice through the API with a cache breakpoint set after your system prompt and tools: once appending each new turn normally, and once where you insert a dynamic field (like a live timestamp) into the system prompt before the second call. Compare the <code>cache_read_input_tokens</code> and <code>cache_creation_input_tokens</code> fields in the response usage between the two runs to see the invalidation directly.</p>
    `
  },
  {
    slug: "5-3-compaction-summarization-trap",
    title: "Compaction and the Summarization Trap",
    dek: "Compaction frees context space by condensing history, but over-compacting drops details the model still needs.",
    minutes: 8,
    bodyHtml: `
      <p>As a conversation or agent session runs long, the context window fills up with history: prior user turns, tool calls, tool results, and model reasoning. Compaction is the practice of condensing that older history, typically by summarizing it, to free up room for the conversation to continue without hitting the context limit. It's a necessary technique for any long-running agent, but it is also one of the most common sources of silent, hard-to-diagnose failures in production agentic systems.</p>
      <h2>What compaction is for</h2>
      <p>Without compaction, a long-running agent session simply stops once the context window fills, forcing a hard restart that loses all prior context. Compaction avoids that cliff by periodically replacing a block of older turns with a shorter summary that preserves the gist while shedding the token cost of the full transcript. Done well, this lets an agent run for hours or across many tool calls while staying within budget.</p>
      <h2>The summarization trap</h2>
      <p>The failure mode, often called the summarization trap, is over-compacting: condensing history so aggressively that details the model still actually needs get dropped. This doesn't fail loudly. The agent doesn't crash or throw an error. It keeps producing responses, but those responses become progressively vaguer, more generic, or subtly wrong, because the specific facts that used to ground them (a particular file path, a specific error message, an exact numeric threshold a user specified earlier) were summarized away in favor of a high-level gist. This is worse than a hard failure in some ways, because it's easy to miss in a review and easy to attribute to "the model getting worse" rather than to a context management decision.</p>
      <p>A concrete pattern: an agent debugging a production issue is told the exact stack trace and the exact line number where an exception originated in turn 3. By turn 40, aggressive compaction has folded that into a summary like "investigated an error in the payment module." The agent now reasons about "the payment module" in the abstract instead of the specific function, and its later suggestions become generic advice rather than the targeted fix the original detail would have supported.</p>
      <h3>What to preserve when compacting</h3>
      <p>Good compaction strategy is selective rather than uniform. Details with high reuse value — file paths, exact error text, IDs, numeric parameters, explicit user decisions or constraints — should be preserved verbatim or extracted into a structured note rather than folded into prose summary. Purely conversational scaffolding — pleasantries, exploratory back-and-forth that led nowhere, redundant restatements — is safe to compress hard. The judgment call the exam tests is whether you can distinguish "this history is safe to compress" from "this history contains facts the agent will need to reference precisely later."</p>
      <div class="callout"><b>Exam trap</b> A question describes an agent session where compaction is applied uniformly to all history older than N turns, and later the agent gives an unhelpful, vague answer to a question that depends on a specific detail from an early turn. The trap answer blames the model's reasoning ability or suggests using a bigger/better model. The correct diagnosis is a compaction failure: the summarization step dropped a load-bearing detail. The fix is changing what gets preserved during compaction (or how aggressively/uniformly it compresses), not swapping models.</div>
      <blockquote>Scenario: A coding agent has been working on a refactor for 90 minutes across many tool calls. Early on, the user specified "do not touch anything under the /legacy directory, it's frozen for a migration." At turn 60, a compaction pass summarizes turns 1-40 into a few sentences about "general refactor goals," and the constraint about /legacy is lost. At turn 75, the agent proposes a change that touches a file under /legacy. What went wrong, and how should compaction have been designed? The constraint was a hard user directive with binding force for the rest of the session, not a detail safe to fold into gist-level summary. Compaction should extract explicit constraints like this into a persistent, separately-maintained "active constraints" note that survives every compaction pass untouched, rather than letting them get swept into the same lossy summarization applied to routine exploratory history.</blockquote>
      <h2>Try it</h2>
      <p>Take a long transcript from an agent session you have access to (or simulate one). Manually write a compacted summary of the first half as you'd expect an automated system to produce it, then list every fact in the original transcript that your summary dropped. For each dropped fact, decide whether a later turn in the transcript actually depended on it — that exercise is exactly the audit a good compaction system needs to pass.</p>
    `
  },
  {
    slug: "5-4-idempotency-error-propagation",
    title: "Idempotency and Error Propagation",
    dek: "Idempotent tool calls survive retries safely; error handling should match response severity to failure criticality.",
    minutes: 8,
    bodyHtml: `
      <p>Two related reliability concepts govern how an agentic system behaves when things go wrong or get repeated: idempotency, which governs what happens when an action runs more than once, and error propagation, which governs how a failure in one step should affect the rest of the system.</p>
      <h2>Idempotency: running twice equals running once</h2>
      <p>A tool call is idempotent if executing it multiple times produces the same end state as executing it once. This property is required for any action that might be automatically retried, whether by your own orchestration logic after a timeout, by a network layer resending a request, or by an agent itself re-attempting a step it isn't sure succeeded. If a tool call is not idempotent, an automatic retry can cause real, sometimes costly, damage: sending a duplicate notification, charging a customer's card twice, creating two identical support tickets, or double-decrementing inventory.</p>
      <p>The design fix is not "avoid retries" — retries are essential for reliability against transient failures — but to make actions safe to retry. The standard technique is an idempotency key: a unique identifier attached to a logical operation (not to each individual HTTP attempt) so that the receiving system can recognize "I've already done this exact operation" and return the prior result instead of executing it again. Reads are naturally idempotent. Writes that use "set to value X" semantics are often naturally idempotent. Writes that use "increment by X" or "send a message" semantics are not, and need explicit guarding — an idempotency key, a check-before-act pattern, or a dedup table — before they're safe to expose to a retry-capable agent loop.</p>
      <h3>Which actions need explicit guards</h3>
      <p>Not every tool call needs this treatment equally. The judgment call is identifying which actions are non-idempotent and consequential enough to guard explicitly. Sending an email, charging a payment method, posting a public message, or triggering an irreversible external side effect are the clearest cases: these need an idempotency key or equivalent guard before they're wired into any agent that might retry automatically. A read-only lookup or a query against a cache needs no such guard, because repeating it changes nothing.</p>
      <h2>Error propagation: match response to criticality</h2>
      <p>When a step in an agent's workflow fails, the correct response depends entirely on what kind of failure it is, and a single blanket policy applied to every error is a design flaw the exam tests directly. There are three broad categories worth distinguishing. First, errors that invalidate the task entirely — a required input turns out to be malformed in a way that makes the rest of the plan meaningless — should halt execution rather than continuing on a broken premise. Second, transient errors — a rate limit, a timeout, a momentary network blip — should trigger a retry, typically with backoff, because the same call is likely to succeed shortly after. Third, non-critical errors — a supplementary lookup fails but the core task can still complete with slightly reduced quality — should trigger degrade-and-continue behavior, where the agent proceeds without that piece of information rather than stopping the whole task over it.</p>
      <p>Applying one policy uniformly — always retry everything, or halt on any error, or silently swallow every failure — produces systems that either loop forever on unrecoverable errors, stop unnecessarily on minor hiccups, or silently produce degraded output without any signal that something went wrong.</p>
      <div class="callout"><b>Exam trap</b> A question offers an error-handling policy that "retries every failed tool call up to three times before giving up" as if this were a complete, sound strategy, then describes an agent that ends up sending three duplicate charge requests after retrying a payment call that actually succeeded but timed out on the response. The trap is treating "always retry" as inherently safe. The correct answer identifies two separate missing pieces: the payment call needed an idempotency key (so the retry would have been safe even though it happened), and blanket retry-everything policies don't distinguish transient failures from ones where retrying is actively dangerous.</div>
      <blockquote>Scenario: An agent's workflow has three steps: (1) look up a customer's account, (2) validate a discount code against a rules engine, (3) apply the discount and email the customer a confirmation. The rules engine call in step 2 times out. What should happen? Because step 2's failure is transient (a timeout, not a data problem) and step 3 depends on its result, the correct response is retry with backoff on step 2, not halt and not skip. If instead step 1 failed because the customer ID doesn't exist, that invalidates the whole task and should halt immediately — retrying it will never succeed. And if step 3's email confirmation fails after the discount was successfully applied, that's non-critical relative to the core task (the discount is applied, which is the business-critical outcome) — log the failure and degrade-and-continue rather than rolling back or halting, though the email step itself should still use an idempotency key so a retry there doesn't send two confirmations.</blockquote>
      <h2>Try it</h2>
      <p>Pick a tool you'd expose to an agent that has a real side effect (sending a message, writing a record, charging something). Design an idempotency key for it: decide what identifies "the same logical operation" across retries (not the same HTTP request, the same intended action), where that key would be generated, and how the receiving system would check it before executing.</p>
    `
  },
  {
    slug: "5-5-escalation-ambiguity",
    title: "Escalation on Ambiguity",
    dek: "Escalate to a human only when a decision is high-stakes, hard to reverse, and confidence is genuinely low.",
    minutes: 7,
    bodyHtml: `
      <p>An agent operating autonomously will regularly encounter situations where it isn't fully certain what the right action is. The question this domain tests is not whether agents should ever ask for help, but under what specific conditions escalating to a human is the correct call versus simply making the best available judgment and proceeding.</p>
      <h2>The three-part test</h2>
      <p>Escalation is warranted when three conditions hold together: the decision is <strong>high-stakes</strong>, the action is <strong>hard to reverse</strong>, and the agent's <strong>confidence is low</strong>. All three matter, and the exam specifically tests whether you'll escalate on just one or two of these being true. A decision can be high-stakes and irreversible but still not warrant escalation if the agent is highly confident in the right action based on clear instructions or unambiguous data. A decision can involve real uncertainty but not warrant escalation if the stakes are low or the action is trivially reversible — in that case, the right move is usually to make a reasonable choice, proceed, and let a subsequent step or a human correct course later if needed.</p>
      <p>This is a deliberate design constraint against the two easy failure modes. An agent that escalates on every uncertain judgment call becomes useless — it turns into a chain of human-approval requests that defeats the purpose of automation and produces "escalation fatigue," where humans stop reading the requests carefully because there are too many of them, including trivial ones. An agent that never escalates, on the other hand, will eventually take an irreversible, high-stakes action on a low-confidence guess, which is the exact scenario escalation exists to prevent.</p>
      <h3>Routine judgment calls are not escalation triggers</h3>
      <p>Most ambiguity an agent encounters is routine: which of two reasonably similar phrasings to use, which of several valid file locations to put a new module in, how to interpret a slightly underspecified but low-consequence instruction. These should be resolved by the agent making its best call, ideally stating its assumption explicitly in its output so a human reviewing the result later can catch and correct it if needed. Reserving escalation for the narrow, genuinely high-stakes-and-irreversible-and-uncertain intersection is what keeps the mechanism useful.</p>
      <div class="callout"><b>Exam trap</b> A question describes an agent that pauses and asks for human confirmation before renaming a local variable in a private helper function, because "it wasn't 100% sure the new name was better." This is framed as admirably cautious. It is not — a variable rename in a private function is low-stakes and trivially reversible (a code review or a follow-up commit fixes it instantly), so this is escalation fatigue in miniature, not good judgment. Contrast with a question where an agent proceeds to delete a production database table without confirmation because it was "reasonably confident" the table was unused — that's the opposite failure, proceeding on insufficient confidence when the action is high-stakes and irreversible.</div>
      <blockquote>Scenario: An agent managing infrastructure-as-code is asked to "clean up unused resources" and finds a storage bucket with no read/write activity in the logs for 90 days, but the bucket's name suggests it might be a disaster-recovery backup target that legitimately sees no routine traffic. Should it escalate? Deleting a storage bucket is hard to reverse (data loss, assuming no separate backup), the stakes are high if it turns out to be load-bearing, and the agent's confidence about its actual purpose is genuinely low given the ambiguous signal from the name. All three conditions hold, so this should escalate with a clear summary: what the agent found, why the name suggests uncertainty, and what evidence would resolve it, rather than either deleting the bucket or silently skipping it without flagging the ambiguity to anyone.</blockquote>
      <h2>Try it</h2>
      <p>List five decisions a coding agent working in your codebase might face in a normal week (examples: renaming a function, deleting a seemingly-unused file, changing a default config value, modifying a database migration, updating a dependency version). For each, score it on the three axes — stakes, reversibility, and your confidence in the right call — and decide which ones genuinely clear the bar for escalation versus which are routine judgment calls the agent should just make and note.</p>
    `
  },
  {
    slug: "5-6-evals-provenance",
    title: "Evals and Information Provenance",
    dek: "Evals catch regressions systematically, and provenance tracking prevents misplaced trust in conflicting context.",
    minutes: 7,
    bodyHtml: `
      <p>This closing topic covers two practices that make an agentic system trustworthy over time rather than just impressive in a single demo: evals, which catch regressions before they ship, and information provenance, which tracks where each piece of context came from so it gets trusted appropriately.</p>
      <h2>Evals: a structured test suite for behavior, not just output format</h2>
      <p>An eval, in this context, is a structured test suite that scores an agent's or prompt's outputs against expected behavior across a representative set of inputs. It is the equivalent of a unit test suite for a component whose behavior is defined by a natural-language prompt and a model rather than by deterministic code. Without evals, changes to a system prompt, a tool definition, or a model version are validated by spot-checking a handful of examples, which reliably misses regressions that only show up on inputs outside whatever the developer happened to try.</p>
      <p>A good eval suite has a few properties worth naming precisely. It covers a representative range of inputs, including edge cases and known-hard cases, not just the happy path. It scores against defined expected behavior — which for agentic tasks often can't be exact-string matching, and instead uses techniques like checking that a tool call sequence matches an expected set, that specific facts appear in the output, or grading by a separate model-as-judge call against a rubric. Crucially, it runs automatically and repeatedly, on every meaningful change, not just once at initial launch. The exam scenario to recognize is any situation where a team changes a prompt, ships it, and only discovers a regression from user complaints — that's precisely the gap evals are meant to close, and the correct answer to "how could this have been caught earlier" is almost always "with an eval suite run before shipping," not "with more careful manual review."</p>
      <h2>Information provenance: know where a fact came from</h2>
      <p>Information provenance is tracking the origin of a piece of context: which tool call produced it, which file it was read from, which turn of the conversation introduced it, or which external source supplied it. This matters most sharply when an agent is reconciling two pieces of information that conflict. Without provenance, the agent (or a human reviewing its output) has no principled way to decide which source to trust — it can only guess, or default to whichever appeared most recently, which is not a reliable trust signal on its own.</p>
      <p>With provenance tracked, the agent can reason about trust properly: a fact pulled directly from a verified database record generally deserves more trust than a fact pulled from a user's casual restatement of something they half-remember, and a fact from a tool call made three turns ago against live data deserves more trust than a stale fact carried in a compacted summary from much earlier in the session. Provenance also supports auditability after the fact — when an agent's output turns out to be wrong, being able to trace the specific tool call or file that supplied the faulty premise is what makes the failure fixable rather than mysterious.</p>
      <div class="callout"><b>Exam trap</b> A question describes an agent that receives conflicting information — a file comment saying a function is deprecated, and a live API response showing the function is still actively called by other services — and picks the file comment because it's "more specific." The trap is treating specificity of wording as a proxy for trustworthiness. The correct reasoning is provenance-based: a live API response reflecting current system state is a more reliable signal of present reality than a code comment, which can go stale the moment the code around it changes and nobody updates the comment. The agent should weight the live data higher and flag the conflict rather than confidently picking the more specific-sounding source.</div>
      <blockquote>Scenario: An agent tasked with answering "is feature X enabled for customer Y" finds two pieces of context: a support ticket from two weeks ago where an engineer wrote "we turned this on for them," and a live query against the feature-flag service returning enabled: false for that customer. Which does it trust, and how should it respond? The live feature-flag query has stronger provenance for this specific question — it's a direct, current read of the actual system of record, whereas the support ticket is a secondhand, dated human statement that could be inaccurate even at the time or since reverted. The agent should answer based on the live flag state, but because the two sources genuinely conflict, it should surface both in its response rather than silently discarding the ticket, since the discrepancy itself (was it turned off again? was the ticket wrong?) may be exactly what the requester needs to know.</blockquote>
      <h2>Try it</h2>
      <p>Take a prompt or agent behavior you maintain, and write three eval cases for it: one clear happy-path input with a specific expected output or tool-call sequence, one edge case you know is tricky, and one adversarial or malformed input. Then write down, for each, how you'd score pass/fail programmatically rather than by eyeballing it — that scoring rule is the part most people skip and the part that actually makes an eval suite catch regressions automatically.</p>
    `
  },
];
