// Generated by `node scripts/export-content.mjs` from Redis (content:reference).
// Edit content in Redis and re-run the export, not this file directly.
export const REFERENCE = {
  "1": {
    "rules": [
      [
        "Loop control signal",
        "Branch only on <code>stop_reason</code> (<code>tool_use</code> vs <code>end_turn</code>). Never parse assistant text for intent, and never use an iteration counter as the primary termination mechanism — it's a safety cap, not the control flow."
      ],
      [
        "Choosing an orchestration pattern",
        "Ordered, predictable subtasks → <b>prompt chaining</b>. Distinct input categories → <b>routing</b>. Independent subtasks or need for consensus → <b>parallelization</b>. Unpredictable decomposition → <b>orchestrator-workers</b>. Clear quality bar, generation alone unreliable → <b>evaluator-optimizer</b>."
      ],
      [
        "Subagent communication",
        "Hub-and-spoke only. Subagents talk to the orchestrator, never to each other. A subagent returns a final result, not its full transcript."
      ],
      [
        "Context to give a subagent",
        "The minimum needed for its scoped task — not the orchestrator's full history. Isolation protects focus and token cost."
      ],
      [
        "Default failure mode to avoid",
        "Treating premature termination (stopping before <code>tool_use</code> resolves) and infinite fallback loops (never respecting a real <code>end_turn</code>) as equally likely exam traps — both come from not trusting <code>stop_reason</code> alone."
      ]
    ]
  },
  "2": {
    "rules": [
      [
        "What makes a good tool",
        "A precise, example-rich description matters more than a clever name. The model chooses tools based on the description text."
      ],
      [
        "tool_use vs tool_result",
        "<code>tool_use</code> is emitted by the model (request to call). <code>tool_result</code> is sent by the client (the outcome), matched by id."
      ],
      [
        "MCP vocabulary",
        "Server = exposes capabilities. Client = 1:1 connection to a server. Host = the application (e.g. Claude Code) managing multiple clients. Primitives = Tools (model-invoked), Resources (contextual data), Prompts (templates)."
      ],
      [
        "Transport choice",
        "Local/trusted process → stdio. Remote or shared → Streamable HTTP."
      ],
      [
        "Error handling",
        "Always return structured, actionable errors (<code>is_error:true</code> + clear message) — never a raw stack trace — so the model can self-correct on retry."
      ],
      [
        "Built-in tool vs MCP vs skill",
        "One-off local capability → built-in tool if one exists. Shared/external system integration → MCP server. Team workflow, no external system → skill or slash command."
      ]
    ]
  },
  "3": {
    "rules": [
      [
        "CLAUDE.md hierarchy",
        "Enterprise → user → project → local. All applicable levels are merged into context — a more specific file adds to the others, it does not replace them."
      ],
      [
        "Slash command vs skill",
        "Slash command: user types it explicitly. Skill: Claude decides on its own to invoke it based on relevance. If the scenario needs autonomous judgment, it's a skill."
      ],
      [
        "Hooks vs prompted instructions",
        "Use a hook when behavior must be deterministic and non-negotiable (e.g. always run linter before commit). A prompted instruction alone is not reliable enough for hard requirements."
      ],
      [
        "Plan mode",
        "Use when changes are risky, hard to reverse, or need human sign-off before execution. It is read-only until explicitly approved."
      ],
      [
        "Permissions design",
        "Grant the narrowest permission set that still lets the workflow complete — not blanket allow, not blanket ask."
      ],
      [
        "Headless / CI use",
        "Non-interactive runs need permissions configured up front; there's no interactive prompt to fall back on mid-run."
      ]
    ]
  },
  "4": {
    "rules": [
      [
        "Where instructions live",
        "System prompt: role, constraints, behavior for the whole conversation. User message: per-turn task/content. Don't put per-turn specifics in the system prompt."
      ],
      [
        "When to use few-shot",
        "Desired output format is precise but hard to describe in words — show, don't just tell."
      ],
      [
        "When to use chain-of-thought",
        "Genuinely multi-step reasoning tasks. Skip it for simple lookups or classification — it adds latency/cost without benefit."
      ],
      [
        "Guaranteeing format",
        "Prefill the start of the response (e.g. with <code>{</code>) to force structure at the source, then validate the full output against a schema."
      ],
      [
        "Handling invalid structured output",
        "Re-prompt with the specific validation error, not a generic 'try again.' A bare retry tends to repeat the same mistake."
      ],
      [
        "Batch vs real-time",
        "Large non-interactive workload, latency not critical → Batches API. Anything a user is waiting on → standard synchronous call."
      ],
      [
        "Self-review anti-pattern",
        "A single call asked to generate and then check its own work tends to rubber-stamp itself. Use a separate call/pass for review."
      ]
    ]
  },
  "5": {
    "rules": [
      [
        "What counts against the context budget",
        "System prompt + tool definitions + retrieved data + conversation history — all of it, not just the visible chat text."
      ],
      [
        "Prompt caching mechanics",
        "Only the stable prefix before the first change is reused. Append new content after the cached prefix to keep hitting cache."
      ],
      [
        "Compaction trade-off",
        "Summarize to free space, but don't over-compact — the 'summarization trap' drops details the model still needs, producing vague later answers."
      ],
      [
        "Escalate vs proceed",
        "Escalate to a human when the decision is high-stakes AND hard to reverse AND confidence is low. Routine, reversible calls don't need escalation."
      ],
      [
        "Error propagation choice",
        "Match the response to criticality: halt on errors that invalidate the task, retry on transient ones, degrade-and-continue on non-critical ones. Never a single blanket policy."
      ],
      [
        "Idempotency",
        "Required for any tool call that might be automatically retried — guard non-idempotent actions (sending a message, charging a card) explicitly."
      ],
      [
        "Codebase exploration strategy",
        "Targeted grep/search before reading whole files. Reflexively reading an entire large repo wastes context budget the exam expects you to protect."
      ]
    ]
  }
};
