#!/usr/bin/env node
// Pulls editorial content back OUT of Redis and regenerates the local data
// modules (js/blueprint-domains.js, js/certs.js, js/faq.js, content/*.mjs).
// Redis is the canonical source; these files are a generated, git-tracked
// cache of it that build-pages.mjs and the browser bundle actually import —
// keeps the deploy static/fast and lets the site still build if Redis is
// briefly unavailable. Content workflow: edit in Redis -> run this -> run
// `node scripts/build-pages.mjs` -> commit -> deploy.
//
// Run: node --env-file=.env.local scripts/export-content.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { getRedis, CONTENT_KEYS, DOMAIN_IDS } from "./redis-client.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const redis = getRedis();

function write(path, contents) {
  writeFileSync(join(ROOT, path), contents);
  console.log(`wrote ${path}`);
}

const banner = (key) =>
  `// Generated by \`node scripts/export-content.mjs\` from Redis (${key}).\n` +
  `// Edit content in Redis and re-run the export, not this file directly.\n`;

async function main() {
  const [domains, certs, mechanics, faq, glossary, reference, blog] = await Promise.all([
    redis.get(CONTENT_KEYS.domains),
    redis.get(CONTENT_KEYS.certs),
    redis.get(CONTENT_KEYS.mechanics),
    redis.get(CONTENT_KEYS.faq),
    redis.get(CONTENT_KEYS.glossary),
    redis.get(CONTENT_KEYS.reference),
    redis.get(CONTENT_KEYS.blog)
  ]);

  const missing = Object.entries({ domains, certs, mechanics, faq, glossary, reference, blog })
    .filter(([, v]) => v == null).map(([k]) => k);
  if (missing.length) {
    console.error(`Missing content in Redis: ${missing.join(", ")}. Run seed-content.mjs first.`);
    process.exit(1);
  }

  write("js/blueprint-domains.js",
    banner(CONTENT_KEYS.domains) +
    `export const DOMAINS_LIST = ${JSON.stringify(domains, null, 2)};\n`);

  write("js/certs.js",
    banner(CONTENT_KEYS.certs) +
    `export const CERTS = ${JSON.stringify(certs, null, 2)};\n\n` +
    `export const UPCOMING_TRACK_MECHANICS = ${JSON.stringify(mechanics)};\n`);

  write("js/faq.js",
    banner(CONTENT_KEYS.faq) +
    `export const FAQ_ITEMS = ${JSON.stringify(faq, null, 2)};\n`);

  write("content/glossary.mjs",
    banner(CONTENT_KEYS.glossary) +
    `export const GLOSSARY = ${JSON.stringify(glossary, null, 2)};\n`);

  write("content/reference.mjs",
    banner(CONTENT_KEYS.reference) +
    `export const REFERENCE = ${JSON.stringify(reference, null, 2)};\n`);

  write("content/blog-posts.mjs",
    banner(CONTENT_KEYS.blog) +
    `export const POSTS = ${JSON.stringify(blog, null, 2)};\n`);

  for (const id of DOMAIN_IDS) {
    const [lessons, handbook] = await Promise.all([
      redis.get(CONTENT_KEYS.lessons(id)),
      redis.get(CONTENT_KEYS.handbook(id))
    ]);
    if (lessons == null || handbook == null) {
      console.error(`Missing content in Redis for domain ${id}. Run seed-content.mjs first.`);
      process.exit(1);
    }
    write(`content/lessons-${id}.mjs`,
      banner(CONTENT_KEYS.lessons(id)) +
      `export const LESSONS = ${JSON.stringify(lessons, null, 2)};\n`);
    write(`content/handbook-${id}.mjs`,
      banner(CONTENT_KEYS.handbook(id)) +
      `export const HANDBOOK = ${JSON.stringify(handbook, null, 2)};\n`);
  }

  console.log("\nDone. Now run: node scripts/build-pages.mjs");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
